# app/swagger_config.yaml
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Get Products API"
  description: "API to get products from the database"
paths:
  /items/{id}:
    get:
      description: "Get a product by ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          description: "ID of the product to fetch"
      responses:
        200:
          description: "Successfully fetched product"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
              product:
                type: "object"
                properties:
                  id:
                    type: "integer"
                  name:
                    type: "string"
                  description:
                    type: "string"
                  price:
                    type: "string"
                  created_at:
                    type: "string"
                  userId:
                    type: "string"
                  image_data:
                    type: "string"
                  category_id:
                    type: "integer"
        404:
          description: "Product not found"
